repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        description: Run go fmt on files included in the commit.
        entry: bash -c 'gofmt -l -w .'
        language: system
        pass_filenames: false
        types: [go]
      
      - id: go-vet
        name: go vet
        description: Run go vet on files included in the commit.
        entry: bash -c 'go vet ./...'
        language: system
        pass_filenames: false
        types: [go]
      
      - id: go-test
        name: go test
        description: Run go test on files included in the commit.
        entry: bash -c 'go test ./...'
        language: system
        pass_filenames: false
        types: [go]
      
      - id: golangci-lint
        name: golangci-lint
        description: Run golangci-lint on files included in the commit.
        entry: bash -c 'if command -v golangci-lint &> /dev/null; then golangci-lint run; else echo "golangci-lint not found. Skipping linting."; fi'
        language: system
        pass_filenames: false
        types: [go]
