name: Update Homebrew Formula

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update (e.g., v0.1.6)'
        required: true
        type: string

jobs:
  update-homebrew-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get release info
        id: release-info
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION=${GITHUB_REF#refs/tags/}
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          TARBALL_URL="https://github.com/${{ github.repository }}/archive/refs/tags/${VERSION}.tar.gz"
          echo "tarball_url=$TARBALL_URL" >> $GITHUB_OUTPUT
          SHA256=$(curl -sL $TARBALL_URL | shasum -a 256 | cut -d ' ' -f 1)
          echo "sha256=$SHA256" >> $GITHUB_OUTPUT

      - name: Checkout homebrew-ekslogs repo
        uses: actions/checkout@v4
        with:
          repository: kzcat/homebrew-ekslogs
          path: homebrew-ekslogs
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}

      - name: Update Formula
        run: |
          VERSION=${{ steps.release-info.outputs.version }}
          SHA256=${{ steps.release-info.outputs.sha256 }}
          
          cat ./homebrew/ekslogs.rb.template | \
            sed "s/VERSION/$VERSION/g" | \
            sed "s/SHA256/$SHA256/g" > homebrew-ekslogs/ekslogs.rb
          
          cd homebrew-ekslogs
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add ekslogs.rb
          git commit -m "Update ekslogs to $VERSION"
          git push
